rvm:
  - 1.9.3
  - 1.9.2

env: "RAILS_ENV='test'"

script: "bundle exec rspec spec/"

before_script:
  - "bundle exec rake db:drop db:create db:migrate RAILS_ENV=test"

notifications:
  recipients:
    - henrique.passalini@gmail.com

branches:
  only:
    - master